<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>annotations</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>me.cqp.luohuaming.SteamWatcher.PublicInfos</RootNamespace>
    <AssemblyName>me.cqp.luohuaming.SteamWatcher.PublicInfos</AssemblyName>
    <GenerateAmnManifest>false</GenerateAmnManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Another-Mirai-Native.Abstractions" Version="1.2.4" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="SkiaSharp.HarfBuzz" Version="3.119.4" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\Frame.png" />
  </ItemGroup>
</Project>
